### ISSUE TITLE
Communicate data from TAT into IMAGE-Extension

### ISSUE THREAD

**Issue by VenissaCarolQuadros** [Shared-Reality-Lab/IMAGE-browser#401]
Currently, data like the share code, secret key, graphic etc are only being sent from the IMAGE-Extension to the TAT via local browser storage and making changes on the TAT. However, this is causing some inconsistencies as the changes made on the TAT do not reflect on the extension.

For instance, if the share code and secret key are changed on the TAT, this change is not seen on the extension and the extension continues to publish to the share code it was originally set up to/ it creates a new share code. (This might create some user confusion as the share code set up on the extension is shared to the TAT)

One potential solution is to create an event listener on the extension to listen to changes in the TAT's local browser storage and then make the corresponding changes on the extension.

**Comment by VenissaCarolQuadros** [comment]
@jaydeepsingh25  As per your suggestions, I have made the changes to the TAT to update the local storage and post a message each time the publish toolbox is closed. An updated version is available on the [ext-data-sync](https://github.com/Shared-Reality-Lab/IMAGE-TactileAuthoring/tree/ext-data-sync) branch. 

You can test this version on the server by updating the Dockerfile for tat to pull text-data-sync by using: `RUN git clone https://github.com/Shared-Reality-Lab/IMAGE-TactileAuthoring.git --branch ext-data-sync --depth 1 --single-branch .` instead of the line that is currently pulling main.
and then setting the override to:

```
  tat:
    profiles: [test, default]
    image: "tat:test"
    build:
      context: /<PATH>/IMAGE-server
      dockerfile: /<PATH>/IMAGE-server/services/tat/Dockerfile
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tat.rule=Host(`tat.unicorn.cim.mcgill.ca`)"
      - "traefik.http.routers.tat.tls.certresolver=myresolver"
      - traefik.docker.network=traefik
    environment:
      - SERVER_NAME=unicorn.cim.mcgill.ca
    networks:
      - traefik
```

Alternatively, you can build locally using: 1. npm install 2. npx rollup -c (in packages/svgcanvas) and then repeat npx rollup -c in the root directory 3. npm run start
Let me know if any further changes are required
